spring.application.name=demo
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: postgres # Change if your local setup uses a different password
    jpa:
        hibernate:
            ddl-auto: update # Automatically creates the tables for you
        show-sql: true